### PR TITLE
build: update udev to 0.9

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Add udev update to 0.9
I've bumped this crate to 0.10.0, though may not be needed as I don't see breaking changes on udev?

### CODE REVIEW

**Comment by jeandudey** [comment]
Hey, I've merged it, I'll release 0.10 tomorrow after testing it.

**Comment by tiagolobocastro** [comment]
Hey @jeandudey any chance to get this released?

**Comment by jeandudey** [comment]
Pushed tag https://github.com/jeandudey/tokio-udev/tree/v0.10.0 and also published on [crates.io](https://crates.io/crates/tokio-udev), @tiagolobocastro.

**Comment by tiagolobocastro** [comment]
Awesome, thank you!

**Pull request merged**
