### PR TITLE
Update to Tokio 0.2

### PR DESCRIPTION
**Pull request by xentec**

### CODE REVIEW

**Comment by jeandudey** [comment]
Let me test it first, and merge then.

**Review by jeandudey — APPROVED** [review]
Everything is ok!

**Comment by xentec** [comment]
Thanks for merging! Are you going to release a new version soon? :)

**Comment by jeandudey** [comment]
@xentec currently I can't release the crate due to some limitations I have right now (not being able to release it anytime soon), maybe if I add you as a crate owner could you release it by the moment?

**Comment by jeandudey** [comment]
Released :)

**Pull request merged**
